### ISSUE TITLE
Incorrect Show Alert Embed

### ISSUE THREAD

**Issue by realdevon** [IPLSplatoon/Radia-Productions#6]
Setting no alert will show "No Show" as field title.

![image](https://user-images.githubusercontent.com/20716219/177796998-c9cf16a3-07db-40b4-8481-58142f5f0d74.png)

**Comment by vlee489** [comment]
This is likely a copy-paste mistake I've made during the creation of the bot, but I'll take a look at it later tonight and push out a fix

**Comment by vlee489** [comment]
Fixed in PR #7
